create table if not exists public.social_lead_posts (
  id bigint generated by default as identity primary key,
  platform text not null,
  external_id text not null,
  username text not null,
  text text not null,
  permalink text not null,
  post_timestamp timestamptz not null,
  created_at timestamptz not null default now(),
  unique(platform, external_id)
);

create table if not exists public.social_leads (
  id bigint generated by default as identity primary key,
  platform text not null,
  external_id text not null,
  username text not null,
  score integer not null check (score between 0 and 100),
  reasons jsonb not null default '[]'::jsonb,
  draft_reply text,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(platform, external_id)
);

create table if not exists public.social_lead_replies (
  id bigint generated by default as identity primary key,
  platform text not null,
  external_id text not null,
  username text,
  reply_id text not null,
  replied_at timestamptz not null default now()
);

create index if not exists social_lead_replies_username_time_idx on public.social_lead_replies(lower(username), replied_at desc);
