from __future__ import annotations

from datetime import datetime
from typing import Protocol

from social_lead_hunter.models import QualificationResult, SocialPost


class Storage(Protocol):
    def has_post(self, platform: str, external_id: str) -> bool: ...
    def save_raw_post(self, platform: str, external_id: str, username: str, text: str, permalink: str, timestamp: datetime) -> None: ...
    def save_candidate(self, post: SocialPost, result: QualificationResult, draft_reply: str | None, status: str) -> None: ...
    def mark_replied(self, platform: str, external_id: str, reply_id: str) -> None: ...
    def last_reply_to_user(self, username: str) -> datetime | None: ...
    def replies_since(self, since: datetime) -> list[datetime]: ...
